// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agendamentos": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cliente"
                ],
                "summary": "Agendar horário",
                "parameters": [
                    {
                        "description": "Dados do agendamento",
                        "name": "agendamento",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Agendamento"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Agendamento"
                        }
                    }
                }
            }
        },
        "/agendamentos/cliente/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agendamentos"
                ],
                "summary": "Listar agendamentos do cliente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do cliente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Agendamento"
                            }
                        }
                    }
                }
            }
        },
        "/agendamentos/profissional/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agendamentos"
                ],
                "summary": "Listar agendamentos por profissional",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do profissional",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Agendamento"
                            }
                        }
                    }
                }
            }
        },
        "/cadastro": {
            "post": {
                "description": "Cadastra novo cliente ou profissional no Firestore",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Cadastro de usuário",
                "parameters": [
                    {
                        "description": "Dados do usuário",
                        "name": "usuario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Usuario"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Usuario"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/estabelecimentos": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cliente"
                ],
                "summary": "Listar estabelecimentos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Estabelecimento"
                            }
                        }
                    }
                }
            }
        },
        "/horarios": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Horários"
                ],
                "summary": "Criar horários",
                "parameters": [
                    {
                        "description": "Horário de atendimento",
                        "name": "horario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.HorarioInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/horarios/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Horários"
                ],
                "summary": "Listar horários por profissional",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do profissional",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Horario"
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Autentica um usuário com email e senha",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Login de usuário",
                "parameters": [
                    {
                        "description": "Email e Senha",
                        "name": "credenciais",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Usuario"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/procedimentos": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Procedimentos"
                ],
                "summary": "Criar procedimento",
                "parameters": [
                    {
                        "description": "Procedimento",
                        "name": "procedimento",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Procedimento"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Procedimento"
                        }
                    }
                }
            }
        },
        "/procedimentos/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Procedimentos"
                ],
                "summary": "Listar procedimentos por profissional",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do profissional",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Procedimento"
                            }
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Procedimentos"
                ],
                "summary": "Atualizar procedimento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do procedimento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Procedimento atualizado",
                        "name": "procedimento",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Procedimento"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Procedimentos"
                ],
                "summary": "Deletar procedimento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do procedimento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/upload/{tipo}/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Upload"
                ],
                "summary": "Atualizar imagem do recurso",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tipo do recurso (profissional ou procedimento)",
                        "name": "tipo",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID do recurso",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "URL da imagem",
                        "name": "imagem",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.ImagemInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.ImagemInput": {
            "type": "object",
            "properties": {
                "imagem_url": {
                    "type": "string"
                }
            }
        },
        "models.Agendamento": {
            "type": "object",
            "properties": {
                "cliente_id": {
                    "type": "string"
                },
                "data_hora": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "procedimento": {
                    "type": "string"
                },
                "profissional_id": {
                    "type": "string"
                }
            }
        },
        "models.Estabelecimento": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imagem_url": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "models.Horario": {
            "type": "object",
            "properties": {
                "dia_semana": {
                    "type": "string"
                },
                "disponivel": {
                    "type": "boolean"
                },
                "hora_fim": {
                    "type": "string"
                },
                "hora_inicio": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "profissional_id": {
                    "type": "string"
                }
            }
        },
        "models.HorarioInput": {
            "type": "object",
            "properties": {
                "dias_semana": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "hora_fim": {
                    "type": "string"
                },
                "hora_inicio": {
                    "type": "string"
                },
                "profissional_id": {
                    "type": "string"
                }
            }
        },
        "models.Login": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                }
            }
        },
        "models.Procedimento": {
            "type": "object",
            "properties": {
                "descricao": {
                    "type": "string"
                },
                "duracao_min": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "imagem_url": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "preco": {
                    "type": "number"
                },
                "profissional_id": {
                    "type": "string"
                }
            }
        },
        "models.Usuario": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
